### ISSUE TITLE
Socialization

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#68] opened 2020-01-25 00:34 UTC
The whole time I'm using TD, I thought how about to make TD social?
I'm curious about what the other geeks diary may look like.
Diaries tells a lot about us so let's make friends out of it, friendship is based on common things and diaries are full of information that may be in common with someone else we wanna be friend with.

I know it's too early but as it may take quite a long time to work on, I thought it's better to make the issue at this point.

**Comment by emvigo** [comment] 2020-01-25 20:55
There's the [twtxt project](https://github.com/buckket/twtxt) that already takes a route like that... not exactly, but it can be used like that. I've always thought of Turbo Diary as a saner alternative to jrnl, which I find to be broken by design, especially regarding how it does encryption... so TD was kinda created with privacy/local diaries in mind, not as a social application.

I guess nothing prevents someone to access a Turbo Diary file and make it publicly available through a server, so that a web/dedicated client can read/write to it. The lower abstraction layer td.c is written in a way that could be ported into other projects and the license allows you to just grab the code and almost do whatever you want with it.

Maybe we can provide an API of some sort to allow people a standard way to do the above? Maybe just make Turbo Diart support OStatus? (so that we're not reinventing the wheel). Not sure, so I'm leaving this open while this idea becomes clearer.

**Comment by mahditakrim** [comment] 2020-01-25 23:18
I'm almost agree with you about what you said above , but what I have in my mind is to have three diary modes in TD:
1. personal / encrypted
2. personal
3. social

For social mode we have a website like Turbodiary.com and people just register there and they can push the social diaries from client TD to there and the other people who are following you can read the diaries in website or even in TD client it self.

We can also do socialization stuffs in the website, things like making friend, following, blocking, reporting, suggesting new friend based on keywords on your diary and ...
And for client TD options like sending diaries to other social media such as twitter, instagram, ... at the same time and ...

What I mean is to make TD bigger, What's your take on this?

**Comment by emvigo** [comment] 2020-02-01 20:23
That means creating a whole new social platform... which is way beyond this project goal: to have a simple local diary program (especially one that does encryption right, unlike others). Also, that's completely beyond my abilities as a programmer.  As I mentioned earlier, the code is available for anyone that might give that a try, though. I wouldn't mind in the long term to develop some kind of API that allows for publishing your diary in a web format (e.g. OStatus, as I mentioned earlier), but that would also be somewhat of a stretch from what Turbo Diary is meant to be.
After having a second thought on the matter, I'm closing the issue.

**Closed by emvigo** 2020-02-01 20:23 UTC
Labels: enhancement

**Comment by RibalGZ** [comment] 2020-02-01 22:30
:eyes:

**Comment by mahditakrim** [comment] 2020-02-03 09:47
@RibalGZ ,
What do you think ?

**Comment by RibalGZ** [comment] 2020-02-03 11:42
> 
> 
> @RibalGZ ,
> What do you think ?

There is twtxt for this purpose. A text based format with several implementations which support user interactions and following features.
TurboDiary is aimed to manage personal diaries, and there is no need to get out of that scope.
You can easily parse turbodiary entries to make twtxt though.
In fact, being able to export turbodiaries to the twtxt format by default is something I proposed in the early days of the project. 👀 

🦍!
